import Head from "next/head";
import Topo from "@/componentes/Topo";
import SecaoCapa from "@/componentes/SecaoCapa";
import SecaoProdutos_texto from "@/componentes/SecaoProdutos";
import Cards from "@/componentes/SecaoProdutos/Cards";
import Lista from "@/componentes/SecaoProdutos/lista";
import SecaoSobre from "@/componentes/SecaoSobre";
import Conjunto_Sobre from "@/componentes/SecaoSobre/conjunto";
import SecaoContato from "@/componentes/SecaoContato";
import Conjunto_Contato from "@/componentes/SecaoContato/conjunto";
import Rodape from "@/componentes/Rodape";
import styles from "@/styles/Home.module.css";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <header className={styles.header}><Topo/></header>
            <section className={styles.SecaoCapa}><SecaoCapa/></section>
            <section className={styles.SecaoProdutos}><SecaoProdutos_texto/><Cards/><Lista/></section>
            <section className={styles.SecaoSobre}><SecaoSobre/><Conjunto_Sobre/></section>
            <section className={styles.SecaoContato}><SecaoContato/><Conjunto_Contato/></section>
          <footer className={styles.Rodape}><Rodape/></footer>
            
    </>
  );
}
